/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExerciseRouteImport } from './routes/exercise'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WaterRouteImport } from './routes/water'
import { Route as WeightRouteImport } from './routes/weight'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseRoute = ExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterRoute = WaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightRoute = WeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/exercise': typeof ExerciseRoute
  '/features': typeof FeaturesRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/water': typeof WaterRoute
  '/weight': typeof WeightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/exercise': typeof ExerciseRoute
  '/features': typeof FeaturesRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/water': typeof WaterRoute
  '/weight': typeof WeightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/exercise': typeof ExerciseRoute
  '/features': typeof FeaturesRoute
  '/goals': typeof GoalsRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/water': typeof WaterRoute
  '/weight': typeof WeightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/exercise'
    | '/features'
    | '/goals'
    | '/login'
    | '/meals'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/signup'
    | '/water'
    | '/weight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/exercise'
    | '/features'
    | '/goals'
    | '/login'
    | '/meals'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/signup'
    | '/water'
    | '/weight'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/exercise'
    | '/features'
    | '/goals'
    | '/login'
    | '/meals'
    | '/onboarding'
    | '/progress'
    | '/settings'
    | '/signup'
    | '/water'
    | '/weight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ExerciseRoute: typeof ExerciseRoute
  FeaturesRoute: typeof FeaturesRoute
  GoalsRoute: typeof GoalsRoute
  LoginRoute: typeof LoginRoute
  MealsRoute: typeof MealsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  WaterRoute: typeof WaterRoute
  WeightRoute: typeof WeightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise': {
      id: '/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water': {
      id: '/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof WaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight': {
      id: '/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof WeightRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ExerciseRoute: ExerciseRoute,
  FeaturesRoute: FeaturesRoute,
  GoalsRoute: GoalsRoute,
  LoginRoute: LoginRoute,
  MealsRoute: MealsRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  WaterRoute: WaterRoute,
  WeightRoute: WeightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
